controllers:
    resource: ../src/Controller/
    type: attribute
app_generate_payment_dates:
    path: /generate-payment-dates
    controller: App\Controller\PaymentDatesController::generatePaymentDates
    methods: GET


welcome:
    path: /
    controller: App\Controller\WelcomeController::index